package bean;
// Generated 08/11/2015 03:24:06 PM by Hibernate Tools 4.3.1



/**
 * AntecedentePersonal generated by hbm2java
 */
public class AntecedentePersonal  implements java.io.Serializable {

private int id_ante_personal;
private String nombre_antecedente;

    public AntecedentePersonal() {
    }

    public int getId_ante_personal() {
        return id_ante_personal;
    }

    public void setId_ante_personal(int id_ante_personal) {
        this.id_ante_personal = id_ante_personal;
    }

    public String getNombre_antecedente() {
        return nombre_antecedente;
    }

    public void setNombre_antecedente(String nombre_antecedente) {
        this.nombre_antecedente = nombre_antecedente;
    }




}


