package bean;
// Generated 08/11/2015 03:24:06 PM by Hibernate Tools 4.3.1



/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  {
    private int id_det_compra;
    private int id_producto;
    private int id_compra;
    private String descripcion;
    private double cantidad;
    private double precio_unitario;
    private double importe;

    public DetalleCompra() {
    }

    public int getId_det_compra() {
        return id_det_compra;
    }

    public void setId_det_compra(int id_det_compra) {
        this.id_det_compra = id_det_compra;
    }

    public int getId_producto() {
        return id_producto;
    }

    public void setId_producto(int id_producto) {
        this.id_producto = id_producto;
    }

    public int getId_compra() {
        return id_compra;
    }

    public void setId_compra(int id_compra) {
        this.id_compra = id_compra;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public double getCantidad() {
        return cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    public double getPrecio_unitario() {
        return precio_unitario;
    }

    public void setPrecio_unitario(double precio_unitario) {
        this.precio_unitario = precio_unitario;
    }

    public double getImporte() {
        return importe;
    }

    public void setImporte(double importe) {
        this.importe = importe;
    }

}


