package bean;
// Generated 08/11/2015 03:24:06 PM by Hibernate Tools 4.3.1



/**
 * HistDiagnostDefId generated by hbm2java
 */
public class HistDiagnostDefId  implements java.io.Serializable {


     private int idDiagnosticoDef;
     private int idHistoriaClinica;

    public HistDiagnostDefId() {
    }

    public HistDiagnostDefId(int idDiagnosticoDef, int idHistoriaClinica) {
       this.idDiagnosticoDef = idDiagnosticoDef;
       this.idHistoriaClinica = idHistoriaClinica;
    }
   
    public int getIdDiagnosticoDef() {
        return this.idDiagnosticoDef;
    }
    
    public void setIdDiagnosticoDef(int idDiagnosticoDef) {
        this.idDiagnosticoDef = idDiagnosticoDef;
    }
    public int getIdHistoriaClinica() {
        return this.idHistoriaClinica;
    }
    
    public void setIdHistoriaClinica(int idHistoriaClinica) {
        this.idHistoriaClinica = idHistoriaClinica;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HistDiagnostDefId) ) return false;
		 HistDiagnostDefId castOther = ( HistDiagnostDefId ) other; 
         
		 return (this.getIdDiagnosticoDef()==castOther.getIdDiagnosticoDef())
 && (this.getIdHistoriaClinica()==castOther.getIdHistoriaClinica());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDiagnosticoDef();
         result = 37 * result + this.getIdHistoriaClinica();
         return result;
   }   


}


