package bean;
// Generated 08/11/2015 03:24:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pieza generated by hbm2java
 */
public class Pieza  implements java.io.Serializable {


     private String id_pieza;
     private String nro_pieza;

    public Pieza() {
    }

    public String getId_pieza() {
        return id_pieza;
    }

    public void setId_pieza(String id_pieza) {
        this.id_pieza = id_pieza;
    }

    public String getNro_pieza() {
        return nro_pieza;
    }

    public void setNro_pieza(String nro_pieza) {
        this.nro_pieza = nro_pieza;
    }
     
     
     
    }


