package bean;
// Generated 08/11/2015 03:24:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio {
     private int id_servicio;
     private int id_cat_serv;
     private String nombre_serv;
     private BigDecimal precio_max;
     private BigDecimal precio_min;
     private String estado;

    public Servicio() {
    }

    public int getId_servicio() {
        return id_servicio;
    }

    public void setId_servicio(int id_servicio) {
        this.id_servicio = id_servicio;
    }

    public int getId_cat_serv() {
        return id_cat_serv;
    }

    public void setId_cat_serv(int id_cat_serv) {
        this.id_cat_serv = id_cat_serv;
    }

    public String getNombre_serv() {
        return nombre_serv;
    }

    public void setNombre_serv(String nombre_serv) {
        this.nombre_serv = nombre_serv;
    }

    public BigDecimal getPrecio_max() {
        return precio_max;
    }

    public void setPrecio_max(BigDecimal precio_max) {
        this.precio_max = precio_max;
    }

    public BigDecimal getPrecio_min() {
        return precio_min;
    }

    public void setPrecio_min(BigDecimal precio_min) {
        this.precio_min = precio_min;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }
     
     
     
    }


