package bean;
// Generated 08/11/2015 03:24:06 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable{



     private String idUsuario="";
     private String login="";
     private String password="";
     private String idRol="";
     private String estado="";

    public Usuario() {
    }

	
    public Usuario(String idUsuario, String login, String password, String estado) {
        this.idUsuario = idUsuario;
        this.login = login;
        this.password = password;
        this.estado = estado;
    }
    public Usuario(String idUsuario, String login, String password, String idRol, String estado) {
       this.idUsuario = idUsuario;
       this.login = login;
       this.password = password;
       this.idRol = idRol;
       this.estado = estado;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(String idRol) {
        this.idRol = idRol;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }



}


