package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private int idCita;
     private Contrato contrato;
     private Empleado empleado;
     private Date fechaCita;
     private Date hora;
     private String estado;
     private String condicion;
     private Set detConsultaServs = new HashSet(0);

    public Cita() {
    }

	
    public Cita(int idCita, Contrato contrato, Empleado empleado, Date fechaCita, Date hora, String estado, String condicion) {
        this.idCita = idCita;
        this.contrato = contrato;
        this.empleado = empleado;
        this.fechaCita = fechaCita;
        this.hora = hora;
        this.estado = estado;
        this.condicion = condicion;
    }
    public Cita(int idCita, Contrato contrato, Empleado empleado, Date fechaCita, Date hora, String estado, String condicion, Set detConsultaServs) {
       this.idCita = idCita;
       this.contrato = contrato;
       this.empleado = empleado;
       this.fechaCita = fechaCita;
       this.hora = hora;
       this.estado = estado;
       this.condicion = condicion;
       this.detConsultaServs = detConsultaServs;
    }
   
    public int getIdCita() {
        return this.idCita;
    }
    
    public void setIdCita(int idCita) {
        this.idCita = idCita;
    }
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public Set getDetConsultaServs() {
        return this.detConsultaServs;
    }
    
    public void setDetConsultaServs(Set detConsultaServs) {
        this.detConsultaServs = detConsultaServs;
    }




}


