package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private Persona persona;
     private Set historiaClinicas = new HashSet(0);
     private Set consultas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, Persona persona) {
        this.idCliente = idCliente;
        this.persona = persona;
    }
    public Cliente(int idCliente, Persona persona, Set historiaClinicas, Set consultas) {
       this.idCliente = idCliente;
       this.persona = persona;
       this.historiaClinicas = historiaClinicas;
       this.consultas = consultas;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getHistoriaClinicas() {
        return this.historiaClinicas;
    }
    
    public void setHistoriaClinicas(Set historiaClinicas) {
        this.historiaClinicas = historiaClinicas;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


