package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private String idConsulta;
     private Cliente cliente;
     private Empleado empleado;
     private String especificaciones;
     private String observaciones;
     private String pronostico;
     private Set contratos = new HashSet(0);

    public Consulta() {
    }

	
    public Consulta(String idConsulta, Cliente cliente, Empleado empleado) {
        this.idConsulta = idConsulta;
        this.cliente = cliente;
        this.empleado = empleado;
    }
    public Consulta(String idConsulta, Cliente cliente, Empleado empleado, String especificaciones, String observaciones, String pronostico, Set contratos) {
       this.idConsulta = idConsulta;
       this.cliente = cliente;
       this.empleado = empleado;
       this.especificaciones = especificaciones;
       this.observaciones = observaciones;
       this.pronostico = pronostico;
       this.contratos = contratos;
    }
   
    public String getIdConsulta() {
        return this.idConsulta;
    }
    
    public void setIdConsulta(String idConsulta) {
        this.idConsulta = idConsulta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getEspecificaciones() {
        return this.especificaciones;
    }
    
    public void setEspecificaciones(String especificaciones) {
        this.especificaciones = especificaciones;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getPronostico() {
        return this.pronostico;
    }
    
    public void setPronostico(String pronostico) {
        this.pronostico = pronostico;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


