package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private int idContrato;
     private Consulta consulta;
     private Date fechaConsult;
     private Date fechaRegistro;
     private Set citas = new HashSet(0);

    public Contrato() {
    }

	
    public Contrato(int idContrato, Consulta consulta, Date fechaConsult, Date fechaRegistro) {
        this.idContrato = idContrato;
        this.consulta = consulta;
        this.fechaConsult = fechaConsult;
        this.fechaRegistro = fechaRegistro;
    }
    public Contrato(int idContrato, Consulta consulta, Date fechaConsult, Date fechaRegistro, Set citas) {
       this.idContrato = idContrato;
       this.consulta = consulta;
       this.fechaConsult = fechaConsult;
       this.fechaRegistro = fechaRegistro;
       this.citas = citas;
    }
   
    public int getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(int idContrato) {
        this.idContrato = idContrato;
    }
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    public Date getFechaConsult() {
        return this.fechaConsult;
    }
    
    public void setFechaConsult(Date fechaConsult) {
        this.fechaConsult = fechaConsult;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


