package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1



/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  implements java.io.Serializable {


     private int idDetalleCompra;
     private Compra compra;
     private Producto producto;
     private String descripcion;
     private Double cantidad;
     private Double precioUnitario;
     private Double importe;

    public DetalleCompra() {
    }

	
    public DetalleCompra(int idDetalleCompra, Compra compra, Producto producto) {
        this.idDetalleCompra = idDetalleCompra;
        this.compra = compra;
        this.producto = producto;
    }
    public DetalleCompra(int idDetalleCompra, Compra compra, Producto producto, String descripcion, Double cantidad, Double precioUnitario, Double importe) {
       this.idDetalleCompra = idDetalleCompra;
       this.compra = compra;
       this.producto = producto;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.importe = importe;
    }
   
    public int getIdDetalleCompra() {
        return this.idDetalleCompra;
    }
    
    public void setIdDetalleCompra(int idDetalleCompra) {
        this.idDetalleCompra = idDetalleCompra;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }




}


