package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DetConsultaServ generated by hbm2java
 */
public class DetConsultaServ  implements java.io.Serializable {


     private int idDetConsultaServ;
     private Cita cita;
     private Empleado empleado;
     private Servicio servicio;
     private BigDecimal cantidad;
     private BigDecimal total;
     private String nroLaboratorioInt;
     private String motivoConsul;
     private Set servicioPiezas = new HashSet(0);

    public DetConsultaServ() {
    }

	
    public DetConsultaServ(int idDetConsultaServ, Cita cita, Empleado empleado, Servicio servicio, BigDecimal total) {
        this.idDetConsultaServ = idDetConsultaServ;
        this.cita = cita;
        this.empleado = empleado;
        this.servicio = servicio;
        this.total = total;
    }
    public DetConsultaServ(int idDetConsultaServ, Cita cita, Empleado empleado, Servicio servicio, BigDecimal cantidad, BigDecimal total, String nroLaboratorioInt, String motivoConsul, Set servicioPiezas) {
       this.idDetConsultaServ = idDetConsultaServ;
       this.cita = cita;
       this.empleado = empleado;
       this.servicio = servicio;
       this.cantidad = cantidad;
       this.total = total;
       this.nroLaboratorioInt = nroLaboratorioInt;
       this.motivoConsul = motivoConsul;
       this.servicioPiezas = servicioPiezas;
    }
   
    public int getIdDetConsultaServ() {
        return this.idDetConsultaServ;
    }
    
    public void setIdDetConsultaServ(int idDetConsultaServ) {
        this.idDetConsultaServ = idDetConsultaServ;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getNroLaboratorioInt() {
        return this.nroLaboratorioInt;
    }
    
    public void setNroLaboratorioInt(String nroLaboratorioInt) {
        this.nroLaboratorioInt = nroLaboratorioInt;
    }
    public String getMotivoConsul() {
        return this.motivoConsul;
    }
    
    public void setMotivoConsul(String motivoConsul) {
        this.motivoConsul = motivoConsul;
    }
    public Set getServicioPiezas() {
        return this.servicioPiezas;
    }
    
    public void setServicioPiezas(Set servicioPiezas) {
        this.servicioPiezas = servicioPiezas;
    }




}


