package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DiagnosticoDef generated by hbm2java
 */
public class DiagnosticoDef  implements java.io.Serializable {


     private int idDiagnosticoDef;
     private String cie10;
     private String descripciN;
     private Set histDiagnostDefs = new HashSet(0);

    public DiagnosticoDef() {
    }

	
    public DiagnosticoDef(int idDiagnosticoDef, String cie10, String descripciN) {
        this.idDiagnosticoDef = idDiagnosticoDef;
        this.cie10 = cie10;
        this.descripciN = descripciN;
    }
    public DiagnosticoDef(int idDiagnosticoDef, String cie10, String descripciN, Set histDiagnostDefs) {
       this.idDiagnosticoDef = idDiagnosticoDef;
       this.cie10 = cie10;
       this.descripciN = descripciN;
       this.histDiagnostDefs = histDiagnostDefs;
    }
   
    public int getIdDiagnosticoDef() {
        return this.idDiagnosticoDef;
    }
    
    public void setIdDiagnosticoDef(int idDiagnosticoDef) {
        this.idDiagnosticoDef = idDiagnosticoDef;
    }
    public String getCie10() {
        return this.cie10;
    }
    
    public void setCie10(String cie10) {
        this.cie10 = cie10;
    }
    public String getDescripciN() {
        return this.descripciN;
    }
    
    public void setDescripciN(String descripciN) {
        this.descripciN = descripciN;
    }
    public Set getHistDiagnostDefs() {
        return this.histDiagnostDefs;
    }
    
    public void setHistDiagnostDefs(Set histDiagnostDefs) {
        this.histDiagnostDefs = histDiagnostDefs;
    }




}


