package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1



/**
 * DiagnosticoPre generated by hbm2java
 */
public class DiagnosticoPre  implements java.io.Serializable {


     private int idDiagnosticoPre;
     private HistoriaClinica historiaClinica;
     private String descripcion;

    public DiagnosticoPre() {
    }

    public DiagnosticoPre(int idDiagnosticoPre, HistoriaClinica historiaClinica, String descripcion) {
       this.idDiagnosticoPre = idDiagnosticoPre;
       this.historiaClinica = historiaClinica;
       this.descripcion = descripcion;
    }
   
    public int getIdDiagnosticoPre() {
        return this.idDiagnosticoPre;
    }
    
    public void setIdDiagnosticoPre(int idDiagnosticoPre) {
        this.idDiagnosticoPre = idDiagnosticoPre;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


