package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Embarazo generated by hbm2java
 */
public class Embarazo  implements java.io.Serializable {


     private int idEmbarazo;
     private HistoriaClinica historiaClinica;
     private String nroSemanas;
     private Date ultimoControl;
     private String trataFarma;

    public Embarazo() {
    }

	
    public Embarazo(int idEmbarazo, HistoriaClinica historiaClinica, String nroSemanas) {
        this.idEmbarazo = idEmbarazo;
        this.historiaClinica = historiaClinica;
        this.nroSemanas = nroSemanas;
    }
    public Embarazo(int idEmbarazo, HistoriaClinica historiaClinica, String nroSemanas, Date ultimoControl, String trataFarma) {
       this.idEmbarazo = idEmbarazo;
       this.historiaClinica = historiaClinica;
       this.nroSemanas = nroSemanas;
       this.ultimoControl = ultimoControl;
       this.trataFarma = trataFarma;
    }
   
    public int getIdEmbarazo() {
        return this.idEmbarazo;
    }
    
    public void setIdEmbarazo(int idEmbarazo) {
        this.idEmbarazo = idEmbarazo;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }
    public String getNroSemanas() {
        return this.nroSemanas;
    }
    
    public void setNroSemanas(String nroSemanas) {
        this.nroSemanas = nroSemanas;
    }
    public Date getUltimoControl() {
        return this.ultimoControl;
    }
    
    public void setUltimoControl(Date ultimoControl) {
        this.ultimoControl = ultimoControl;
    }
    public String getTrataFarma() {
        return this.trataFarma;
    }
    
    public void setTrataFarma(String trataFarma) {
        this.trataFarma = trataFarma;
    }




}


