package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ExamenClinico generated by hbm2java
 */
public class ExamenClinico  implements java.io.Serializable {


     private int idExamenClinico;
     private String aplicadoEn;
     private Set histExamenClinicos = new HashSet(0);

    public ExamenClinico() {
    }

	
    public ExamenClinico(int idExamenClinico, String aplicadoEn) {
        this.idExamenClinico = idExamenClinico;
        this.aplicadoEn = aplicadoEn;
    }
    public ExamenClinico(int idExamenClinico, String aplicadoEn, Set histExamenClinicos) {
       this.idExamenClinico = idExamenClinico;
       this.aplicadoEn = aplicadoEn;
       this.histExamenClinicos = histExamenClinicos;
    }
   
    public int getIdExamenClinico() {
        return this.idExamenClinico;
    }
    
    public void setIdExamenClinico(int idExamenClinico) {
        this.idExamenClinico = idExamenClinico;
    }
    public String getAplicadoEn() {
        return this.aplicadoEn;
    }
    
    public void setAplicadoEn(String aplicadoEn) {
        this.aplicadoEn = aplicadoEn;
    }
    public Set getHistExamenClinicos() {
        return this.histExamenClinicos;
    }
    
    public void setHistExamenClinicos(Set histExamenClinicos) {
        this.histExamenClinicos = histExamenClinicos;
    }




}


