package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GradoInstruccion generated by hbm2java
 */
public class GradoInstruccion  implements java.io.Serializable {


     private int idGradoInstruccion;
     private String nombreGradInst;
     private String estado;
     private Set personas = new HashSet(0);

    public GradoInstruccion() {
    }

	
    public GradoInstruccion(int idGradoInstruccion, String nombreGradInst) {
        this.idGradoInstruccion = idGradoInstruccion;
        this.nombreGradInst = nombreGradInst;
    }
    public GradoInstruccion(int idGradoInstruccion, String nombreGradInst, String estado, Set personas) {
       this.idGradoInstruccion = idGradoInstruccion;
       this.nombreGradInst = nombreGradInst;
       this.estado = estado;
       this.personas = personas;
    }
   
    public int getIdGradoInstruccion() {
        return this.idGradoInstruccion;
    }
    
    public void setIdGradoInstruccion(int idGradoInstruccion) {
        this.idGradoInstruccion = idGradoInstruccion;
    }
    public String getNombreGradInst() {
        return this.nombreGradInst;
    }
    
    public void setNombreGradInst(String nombreGradInst) {
        this.nombreGradInst = nombreGradInst;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


