package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HabitoNocivo generated by hbm2java
 */
public class HabitoNocivo  implements java.io.Serializable {


     private int idHabitoNocivo;
     private String nombreHabNoc;
     private Set histHabNocs = new HashSet(0);

    public HabitoNocivo() {
    }

	
    public HabitoNocivo(int idHabitoNocivo, String nombreHabNoc) {
        this.idHabitoNocivo = idHabitoNocivo;
        this.nombreHabNoc = nombreHabNoc;
    }
    public HabitoNocivo(int idHabitoNocivo, String nombreHabNoc, Set histHabNocs) {
       this.idHabitoNocivo = idHabitoNocivo;
       this.nombreHabNoc = nombreHabNoc;
       this.histHabNocs = histHabNocs;
    }
   
    public int getIdHabitoNocivo() {
        return this.idHabitoNocivo;
    }
    
    public void setIdHabitoNocivo(int idHabitoNocivo) {
        this.idHabitoNocivo = idHabitoNocivo;
    }
    public String getNombreHabNoc() {
        return this.nombreHabNoc;
    }
    
    public void setNombreHabNoc(String nombreHabNoc) {
        this.nombreHabNoc = nombreHabNoc;
    }
    public Set getHistHabNocs() {
        return this.histHabNocs;
    }
    
    public void setHistHabNocs(Set histHabNocs) {
        this.histHabNocs = histHabNocs;
    }




}


