package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HistoriaClinica generated by hbm2java
 */
public class HistoriaClinica  implements java.io.Serializable {


     private int idHistoriaClinica;
     private Cliente cliente;
     private String nroHistoria;
     private String comentario;
     private String antecedentesFamiliar;
     private Date fechaReg;
     private Date horaReg;
     private String responsableApoderado;
     private String motivoConsulta;
     private BigDecimal peso;
     private BigDecimal talla;
     private String pa;
     private String estado;
     private Set histAntePersonals = new HashSet(0);
     private Set histExamenClinicos = new HashSet(0);
     private Set histDiagnostDefs = new HashSet(0);
     private Set histHabNocs = new HashSet(0);
     private Set diagnosticoPres = new HashSet(0);
     private Set embarazos = new HashSet(0);

    public HistoriaClinica() {
    }

	
    public HistoriaClinica(int idHistoriaClinica, Cliente cliente, String nroHistoria, Date fechaReg, Date horaReg, String estado) {
        this.idHistoriaClinica = idHistoriaClinica;
        this.cliente = cliente;
        this.nroHistoria = nroHistoria;
        this.fechaReg = fechaReg;
        this.horaReg = horaReg;
        this.estado = estado;
    }
    public HistoriaClinica(int idHistoriaClinica, Cliente cliente, String nroHistoria, String comentario, String antecedentesFamiliar, Date fechaReg, Date horaReg, String responsableApoderado, String motivoConsulta, BigDecimal peso, BigDecimal talla, String pa, String estado, Set histAntePersonals, Set histExamenClinicos, Set histDiagnostDefs, Set histHabNocs, Set diagnosticoPres, Set embarazos) {
       this.idHistoriaClinica = idHistoriaClinica;
       this.cliente = cliente;
       this.nroHistoria = nroHistoria;
       this.comentario = comentario;
       this.antecedentesFamiliar = antecedentesFamiliar;
       this.fechaReg = fechaReg;
       this.horaReg = horaReg;
       this.responsableApoderado = responsableApoderado;
       this.motivoConsulta = motivoConsulta;
       this.peso = peso;
       this.talla = talla;
       this.pa = pa;
       this.estado = estado;
       this.histAntePersonals = histAntePersonals;
       this.histExamenClinicos = histExamenClinicos;
       this.histDiagnostDefs = histDiagnostDefs;
       this.histHabNocs = histHabNocs;
       this.diagnosticoPres = diagnosticoPres;
       this.embarazos = embarazos;
    }
   
    public int getIdHistoriaClinica() {
        return this.idHistoriaClinica;
    }
    
    public void setIdHistoriaClinica(int idHistoriaClinica) {
        this.idHistoriaClinica = idHistoriaClinica;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getNroHistoria() {
        return this.nroHistoria;
    }
    
    public void setNroHistoria(String nroHistoria) {
        this.nroHistoria = nroHistoria;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getAntecedentesFamiliar() {
        return this.antecedentesFamiliar;
    }
    
    public void setAntecedentesFamiliar(String antecedentesFamiliar) {
        this.antecedentesFamiliar = antecedentesFamiliar;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Date getHoraReg() {
        return this.horaReg;
    }
    
    public void setHoraReg(Date horaReg) {
        this.horaReg = horaReg;
    }
    public String getResponsableApoderado() {
        return this.responsableApoderado;
    }
    
    public void setResponsableApoderado(String responsableApoderado) {
        this.responsableApoderado = responsableApoderado;
    }
    public String getMotivoConsulta() {
        return this.motivoConsulta;
    }
    
    public void setMotivoConsulta(String motivoConsulta) {
        this.motivoConsulta = motivoConsulta;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public BigDecimal getTalla() {
        return this.talla;
    }
    
    public void setTalla(BigDecimal talla) {
        this.talla = talla;
    }
    public String getPa() {
        return this.pa;
    }
    
    public void setPa(String pa) {
        this.pa = pa;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getHistAntePersonals() {
        return this.histAntePersonals;
    }
    
    public void setHistAntePersonals(Set histAntePersonals) {
        this.histAntePersonals = histAntePersonals;
    }
    public Set getHistExamenClinicos() {
        return this.histExamenClinicos;
    }
    
    public void setHistExamenClinicos(Set histExamenClinicos) {
        this.histExamenClinicos = histExamenClinicos;
    }
    public Set getHistDiagnostDefs() {
        return this.histDiagnostDefs;
    }
    
    public void setHistDiagnostDefs(Set histDiagnostDefs) {
        this.histDiagnostDefs = histDiagnostDefs;
    }
    public Set getHistHabNocs() {
        return this.histHabNocs;
    }
    
    public void setHistHabNocs(Set histHabNocs) {
        this.histHabNocs = histHabNocs;
    }
    public Set getDiagnosticoPres() {
        return this.diagnosticoPres;
    }
    
    public void setDiagnosticoPres(Set diagnosticoPres) {
        this.diagnosticoPres = diagnosticoPres;
    }
    public Set getEmbarazos() {
        return this.embarazos;
    }
    
    public void setEmbarazos(Set embarazos) {
        this.embarazos = embarazos;
    }




}


