package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1



/**
 * HistDiagnostDef generated by hbm2java
 */
public class HistDiagnostDef  implements java.io.Serializable {


     private int idHistDiagnostDef;
     private DiagnosticoDef diagnosticoDef;
     private HistoriaClinica historiaClinica;

    public HistDiagnostDef() {
    }

    public HistDiagnostDef(int idHistDiagnostDef, DiagnosticoDef diagnosticoDef, HistoriaClinica historiaClinica) {
       this.idHistDiagnostDef = idHistDiagnostDef;
       this.diagnosticoDef = diagnosticoDef;
       this.historiaClinica = historiaClinica;
    }
   
    public int getIdHistDiagnostDef() {
        return this.idHistDiagnostDef;
    }
    
    public void setIdHistDiagnostDef(int idHistDiagnostDef) {
        this.idHistDiagnostDef = idHistDiagnostDef;
    }
    public DiagnosticoDef getDiagnosticoDef() {
        return this.diagnosticoDef;
    }
    
    public void setDiagnosticoDef(DiagnosticoDef diagnosticoDef) {
        this.diagnosticoDef = diagnosticoDef;
    }
    public HistoriaClinica getHistoriaClinica() {
        return this.historiaClinica;
    }
    
    public void setHistoriaClinica(HistoriaClinica historiaClinica) {
        this.historiaClinica = historiaClinica;
    }




}


