package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ocupacion generated by hbm2java
 */
public class Ocupacion  implements java.io.Serializable {


     private int idOcupacion;
     private String nombreOcupacion;
     private String estado;
     private Set personas = new HashSet(0);

    public Ocupacion() {
    }

	
    public Ocupacion(int idOcupacion, String estado) {
        this.idOcupacion = idOcupacion;
        this.estado = estado;
    }
    public Ocupacion(int idOcupacion, String nombreOcupacion, String estado, Set personas) {
       this.idOcupacion = idOcupacion;
       this.nombreOcupacion = nombreOcupacion;
       this.estado = estado;
       this.personas = personas;
    }
   
    public int getIdOcupacion() {
        return this.idOcupacion;
    }
    
    public void setIdOcupacion(int idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public String getNombreOcupacion() {
        return this.nombreOcupacion;
    }
    
    public void setNombreOcupacion(String nombreOcupacion) {
        this.nombreOcupacion = nombreOcupacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


