package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pieza generated by hbm2java
 */
public class Pieza  implements java.io.Serializable {


     private String idPieza;
     private String nroPieza;
     private Set servicioPiezas = new HashSet(0);

    public Pieza() {
    }

	
    public Pieza(String idPieza, String nroPieza) {
        this.idPieza = idPieza;
        this.nroPieza = nroPieza;
    }
    public Pieza(String idPieza, String nroPieza, Set servicioPiezas) {
       this.idPieza = idPieza;
       this.nroPieza = nroPieza;
       this.servicioPiezas = servicioPiezas;
    }
   
    public String getIdPieza() {
        return this.idPieza;
    }
    
    public void setIdPieza(String idPieza) {
        this.idPieza = idPieza;
    }
    public String getNroPieza() {
        return this.nroPieza;
    }
    
    public void setNroPieza(String nroPieza) {
        this.nroPieza = nroPieza;
    }
    public Set getServicioPiezas() {
        return this.servicioPiezas;
    }
    
    public void setServicioPiezas(Set servicioPiezas) {
        this.servicioPiezas = servicioPiezas;
    }




}


