package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idProveedor;
     private Persona persona;
     private String estado;
     private Set compras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int idProveedor, Persona persona) {
        this.idProveedor = idProveedor;
        this.persona = persona;
    }
    public Proveedor(int idProveedor, Persona persona, String estado, Set compras) {
       this.idProveedor = idProveedor;
       this.persona = persona;
       this.estado = estado;
       this.compras = compras;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


