package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1



/**
 * ServicioPieza generated by hbm2java
 */
public class ServicioPieza  implements java.io.Serializable {


     private ServicioPiezaId id;
     private DetConsultaServ detConsultaServ;
     private Pieza pieza;

    public ServicioPieza() {
    }

    public ServicioPieza(ServicioPiezaId id, DetConsultaServ detConsultaServ, Pieza pieza) {
       this.id = id;
       this.detConsultaServ = detConsultaServ;
       this.pieza = pieza;
    }
   
    public ServicioPiezaId getId() {
        return this.id;
    }
    
    public void setId(ServicioPiezaId id) {
        this.id = id;
    }
    public DetConsultaServ getDetConsultaServ() {
        return this.detConsultaServ;
    }
    
    public void setDetConsultaServ(DetConsultaServ detConsultaServ) {
        this.detConsultaServ = detConsultaServ;
    }
    public Pieza getPieza() {
        return this.pieza;
    }
    
    public void setPieza(Pieza pieza) {
        this.pieza = pieza;
    }




}


