package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private int idServicio;
     private CategoriaServicio categoriaServicio;
     private String nombreServ;
     private BigDecimal precioMax;
     private BigDecimal precioMin;
     private String estado;
     private Set detConsultaServs = new HashSet(0);

    public Servicio() {
    }

	
    public Servicio(int idServicio, CategoriaServicio categoriaServicio, String nombreServ) {
        this.idServicio = idServicio;
        this.categoriaServicio = categoriaServicio;
        this.nombreServ = nombreServ;
    }
    public Servicio(int idServicio, CategoriaServicio categoriaServicio, String nombreServ, BigDecimal precioMax, BigDecimal precioMin, String estado, Set detConsultaServs) {
       this.idServicio = idServicio;
       this.categoriaServicio = categoriaServicio;
       this.nombreServ = nombreServ;
       this.precioMax = precioMax;
       this.precioMin = precioMin;
       this.estado = estado;
       this.detConsultaServs = detConsultaServs;
    }
   
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public CategoriaServicio getCategoriaServicio() {
        return this.categoriaServicio;
    }
    
    public void setCategoriaServicio(CategoriaServicio categoriaServicio) {
        this.categoriaServicio = categoriaServicio;
    }
    public String getNombreServ() {
        return this.nombreServ;
    }
    
    public void setNombreServ(String nombreServ) {
        this.nombreServ = nombreServ;
    }
    public BigDecimal getPrecioMax() {
        return this.precioMax;
    }
    
    public void setPrecioMax(BigDecimal precioMax) {
        this.precioMax = precioMax;
    }
    public BigDecimal getPrecioMin() {
        return this.precioMin;
    }
    
    public void setPrecioMin(BigDecimal precioMin) {
        this.precioMin = precioMin;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDetConsultaServs() {
        return this.detConsultaServs;
    }
    
    public void setDetConsultaServs(Set detConsultaServs) {
        this.detConsultaServs = detConsultaServs;
    }




}


