package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1



/**
 * ServicioPiezaId generated by hbm2java
 */
public class ServicioPiezaId  implements java.io.Serializable {


     private String idPieza;
     private int idDetConsultaServ;

    public ServicioPiezaId() {
    }

    public ServicioPiezaId(String idPieza, int idDetConsultaServ) {
       this.idPieza = idPieza;
       this.idDetConsultaServ = idDetConsultaServ;
    }
   
    public String getIdPieza() {
        return this.idPieza;
    }
    
    public void setIdPieza(String idPieza) {
        this.idPieza = idPieza;
    }
    public int getIdDetConsultaServ() {
        return this.idDetConsultaServ;
    }
    
    public void setIdDetConsultaServ(int idDetConsultaServ) {
        this.idDetConsultaServ = idDetConsultaServ;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServicioPiezaId) ) return false;
		 ServicioPiezaId castOther = ( ServicioPiezaId ) other; 
         
		 return ( (this.getIdPieza()==castOther.getIdPieza()) || ( this.getIdPieza()!=null && castOther.getIdPieza()!=null && this.getIdPieza().equals(castOther.getIdPieza()) ) )
 && (this.getIdDetConsultaServ()==castOther.getIdDetConsultaServ());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPieza() == null ? 0 : this.getIdPieza().hashCode() );
         result = 37 * result + this.getIdDetConsultaServ();
         return result;
   }   


}


