package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDoc generated by hbm2java
 */
public class TipoDoc  implements java.io.Serializable {


     private int idTipoDoc;
     private String nombreTipoDoc;
     private String estado;
     private Set personas = new HashSet(0);

    public TipoDoc() {
    }

	
    public TipoDoc(int idTipoDoc, String nombreTipoDoc, String estado) {
        this.idTipoDoc = idTipoDoc;
        this.nombreTipoDoc = nombreTipoDoc;
        this.estado = estado;
    }
    public TipoDoc(int idTipoDoc, String nombreTipoDoc, String estado, Set personas) {
       this.idTipoDoc = idTipoDoc;
       this.nombreTipoDoc = nombreTipoDoc;
       this.estado = estado;
       this.personas = personas;
    }
   
    public int getIdTipoDoc() {
        return this.idTipoDoc;
    }
    
    public void setIdTipoDoc(int idTipoDoc) {
        this.idTipoDoc = idTipoDoc;
    }
    public String getNombreTipoDoc() {
        return this.nombreTipoDoc;
    }
    
    public void setNombreTipoDoc(String nombreTipoDoc) {
        this.nombreTipoDoc = nombreTipoDoc;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


