package entidad;
// Generated 10/11/2015 02:03:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private int idUnidadMedida;
     private String nombreUniMed;
     private String estado;
     private Set productos = new HashSet(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(int idUnidadMedida, String nombreUniMed) {
        this.idUnidadMedida = idUnidadMedida;
        this.nombreUniMed = nombreUniMed;
    }
    public UnidadMedida(int idUnidadMedida, String nombreUniMed, String estado, Set productos) {
       this.idUnidadMedida = idUnidadMedida;
       this.nombreUniMed = nombreUniMed;
       this.estado = estado;
       this.productos = productos;
    }
   
    public int getIdUnidadMedida() {
        return this.idUnidadMedida;
    }
    
    public void setIdUnidadMedida(int idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }
    public String getNombreUniMed() {
        return this.nombreUniMed;
    }
    
    public void setNombreUniMed(String nombreUniMed) {
        this.nombreUniMed = nombreUniMed;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


